services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - backend_data:/var/www/storage
      - ./dpms-backend:/var/www
    environment:
      - DB_HOST=db
      - DB_DATABASE=dpms
      - DB_USERNAME=dpms_user
      - DB_PASSWORD=dpms_password
    depends_on:
      - db

  node:
    image: node:18.20
    container_name: node
    volumes:
      - ./dpms-backend:/var/www
    working_dir: /var/www
    command: sh -c "npm install && npm run dev"

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - frontend_data:/app/.next
      - ./dpms-frontend:/app
    depends_on:
      - backend

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=dpms
      - MYSQL_USER=dpms_user
      - MYSQL_PASSWORD=dpms_password
      - MYSQL_ROOT_PASSWORD=root_password

volumes:
  backend_data:
  frontend_data:
  mysql_data: